kern: backport updates from Limine templates

diff --git a/kernel/get-deps b/kernel/get-deps
--- a/kernel/get-deps
+++ b/kernel/get-deps
@@ -7,10 +7,6 @@ test -z "$srcdir" && srcdir=.
 
 cd "$srcdir"
 
-FREESTANDING_HEADERS_COMMIT_HASH=dd3abd2d7147efc4170dff478d3b7730bed14147
-FLANTERM_COMMIT_HASH=ef07a10cc38b34aa003d17be97a9f3542e275069
-EYALROZ_PRINTF_COMMIT_HASH=2d75fef6c605e699d2643267cbaeaaa49b0a2635
-
 clone_repo_commit() {
     if test -d $2/.git; then
         git -C $2 reset --hard
@@ -30,11 +26,52 @@ clone_repo_commit() {
     fi
 }
 
-#if test -d .git; then
-    clone_repo_commit https://github.com/osdev0/freestanding-headers.git c/freestanding-headers $FREESTANDING_HEADERS_COMMIT_HASH
-    clone_repo_commit https://github.com/mintsuki/flanterm.git c/flanterm $FLANTERM_COMMIT_HASH
+download_by_hash() {
+    DOWNLOAD_COMMAND="curl -Lo"
+    if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
+        DOWNLOAD_COMMAND="wget -O"
+        if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
+            echo "error: Neither curl nor wget found"
+            exit 1
+        fi
+    fi
+    SHA256_COMMAND="sha256sum"
+    if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
+        SHA256_COMMAND="sha256"
+        if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
+            echo "error: Cannot find sha256(sum) command"
+            exit 1
+        fi
+    fi
+    if ! test -f $2 || ! $SHA256_COMMAND $2 | grep $3 >/dev/null 2>&1; then
+        rm -f $2
+        mkdir -p $2 && rm -rf $2
+        $DOWNLOAD_COMMAND $2 $1
+        if ! $SHA256_COMMAND $2 | grep $3 >/dev/null 2>&1; then
+            echo "error: Cannot download file '$2' by hash"
+            exit 1
+        fi
+    fi
+}
 
-    clone_repo_commit https://github.com/eyalroz/printf.git printf $EYALROZ_PRINTF_COMMIT_HASH
-    mkdir -p c/printf
-    cp printf/src/printf/printf.c printf/src/printf/printf.h c/printf/
-#fi
+if ! test -f version; then
+    clone_repo_commit \
+        https://github.com/osdev0/freestanding-headers.git \
+        c/freestanding-headers \
+        dd3abd2d7147efc4170dff478d3b7730bed14147
+
+    clone_repo_commit \
+        https://github.com/mintsuki/flanterm.git \
+        c/flanterm \
+        ef07a10cc38b34aa003d17be97a9f3542e275069
+
+    download_by_hash \
+        https://github.com/eyalroz/printf/raw/2d75fef6c605e699d2643267cbaeaaa49b0a2635/src/printf/printf.c \
+        c/printf/printf.c \
+        bae9609d84dc7a56ff0b3d0d3787d33edbd1ec224f0f7ff7edefd6b6ae613395
+
+    download_by_hash \
+        https://github.com/eyalroz/printf/raw/2d75fef6c605e699d2643267cbaeaaa49b0a2635/src/printf/printf.h \
+        c/printf/printf.h \
+        f63b84650f29394fd1bc6f6dce889d11570fcc152c5d512bfe6b68174c5aed56
+fi
